### ISSUE TITLE
Median missing

### ISSUE THREAD

**Issue by HKyleZhang** [ropensci/tracerer#24]
I've been using calc_summary_stats_trace() and it didn't report median. Did you intentionally leave it out or was it missed?

**Comment by richelbilderbeek** [comment]
I will take a look today. It should report all stats as reported by Tracer.

**Comment by richelbilderbeek** [comment]
Tracer does report a median: 

![issue](https://user-images.githubusercontent.com/2098230/80374861-a3564280-8897-11ea-9bdf-67d77e0aa7c3.png)

**Comment by richelbilderbeek** [comment]
I see [here](https://github.com/ropensci/tracerer/blob/master/R/calc_summary_stats.R#L107) that I do report a mode, but should report a median instead. 

@HKyleZhang is right: I accidentally report the mode instead of the median!

Will fix now.

**Comment by richelbilderbeek** [comment]
Note to self: the Tracer version tracerer is built on, reports both median and mean:

![screen01](https://user-images.githubusercontent.com/2098230/80375412-89692f80-8898-11ea-8309-cd9ca97ec900.png)

**Comment by richelbilderbeek** [comment]
Note to self: it is fixed, now create new version and such

![fixed](https://user-images.githubusercontent.com/2098230/80376638-6b043380-889a-11ea-83ce-d81fd6b6bb77.png)

**Comment by HKyleZhang** [comment]
Okay. That's great!

**Comment by richelbilderbeek** [comment]
Yes, thanks for sharing :+1:

**Comment by richelbilderbeek** [comment]
Hi @HKyleZhang,

Again, thanks for submitting this Issue! It can be fixed by 

```{r}
remotes::install_github("ropensci/tracerer")
```

Let me know if you find something else that is off :+1:

BTW, I see we are in the same field. Maybe you'd enjoy [babette](https://github.com/ropensci/babette) as well :+1:

Cheers, Richel
