### ISSUE TITLE
can this be used for beast1?

### ISSUE THREAD

**Issue by liamxg** [ropensci/tracerer#25]

**Comment by richelbilderbeek** [comment]
Hi @liamxg, as far as I know, this can be used to parse BEAST (i.e. not BEAST2) output too, as one uses Tracer there too :-)

If not, hit me with a bug report :-) . In the worst case, I will give a 'no' (as I do not intend to maintain BEAST features), but I think you will likelier help the `tracerer` users out :-)

**Comment by liamxg** [comment]
hi @richelbilderbeek thanks for your help, will you keep develop this?

**Comment by richelbilderbeek** [comment]
Hi @liamxg, I indeed still maintain this package. As far as I know, it is feature complete, as it can read all output files created by BEAST2. Am I missing some functionality?

Note that I am not interested in 'nice to have things'  that are beyond the scope of the package: one can create a new package for that :-)

**Comment by liamxg** [comment]
@richelbilderbeek cool!
